### ISSUE TITLE
the "set IP" screen constantly refreshes making it hard to enter one in

### ISSUE THREAD

**Issue by jbranc** [jsoosiah/htp1-custom-controller#1]
the screen looks like it refreshes every few seconds trying to connect. this has the side effect of removing focus from the IP input box and wiping out what you type.  I've only been able to quickly paste an IP in there to get past this screen. luckily its a one-time-per-device thing.

**Comment by jsoosiah** [comment]
Hi, thanks for the report. I wasn't able to reproduce on Windows with FF / Chrome or Android with Chrome. Could you share which device and browser you're seeing the issue with?

**Comment by jbranc** [comment]
I'm seeing it on Edge, Firefox, Chrome and Safari on MacOS (and Safari on iPhone).  Only happens for the first time (i.e. incognito window). Click into the textbox, see that it has focus, and it immediately loses focus and clears the input.  happens every second or two if you keep clicking into it.

**Comment by jbranc** [comment]
bringing this back up - i can't in on my iphone anymore as it keeps flashing. looks like its flashing to the power button screen maybe.  attaching a video.

https://user-images.githubusercontent.com/1193895/122844298-03435000-d2c7-11eb-8cf2-fe034e81b6dd.mov

**Comment by jsoosiah** [comment]
Thanks for the video. It's difficult to determine what's happening since I don't have an iPhone to test, but I can't reproduce on my iPad and I haven't heard similar reports from other users. 

I wonder if there's an issue related to your network configuration, such as a firewall blocking the connection. Does the issue still occur in Chrome on macOS? If so, after reproducing the issue, could you please open the Developer Tools, and share the contents of the Console tab?

**Comment by jbranc** [comment]
sorry for only coming back to this every few months lol

so the error in the console is:
WebSocket connection to 'ws://192.168.1.1/ws/controller' failed: The operation couldn’t be completed. Socket is not connected
and it just loops this every second forever.

and if i go to local storage, the websocketIp value is 192.168.1.1, which is my gateway not my htp-1.  if i edit the value here (using dev tools) to .33 (my htp-1) instead, it snaps into place.  no idea why my gateway is behaving this way. its a UniFi Dream Machine Pro. I do have uPnP enabled.  Dirac, for instance, has no trouble discovering it.

**Comment by jbranc** [comment]
Hello - i see there was a commit above to workaround the issue, but its still happening for me.  Is there anything I need to do to use the update?

i periodically attach my phone to my mac to use devtools and set the websocketip value in local storage to the right one. however, eventually it goes back to the .1 address and starts back into its infinite loop

**Comment by jsoosiah** [comment]
If you're using the website, the update has been deployed so no need to do anything on your end. 

I have a few other ideas to try. Give me a few days and I'll post again when I push an update.

**Comment by jsoosiah** [comment]
@jbranc I've deployed another test fix for you to try. Please let me know if it makes any difference for you.

**Comment by jbranc** [comment]
success!! thank you!
